# Generated by Django 5.0.7 on 2024-11-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_departamento", models.CharField(max_length=16, unique=True)),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_proveedor", models.CharField(max_length=16, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("calle", models.CharField(max_length=30)),
                ("numero", models.CharField(max_length=6)),
                ("ciudad", models.CharField(max_length=30)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ARICA_PARINACOTA", "XV Región de Arica y Parinacota"),
                            ("TARAPACA", "I Región de Tarapacá"),
                            ("ANTOFAGASTA", "II Región de Antofagasta"),
                            ("ATACAMA", "III Región de Atacama"),
                            ("COQUIMBO", "IV Región de Coquimbo"),
                            ("VALPARAISO", "V Región de Valparaíso"),
                            ("METROPOLITANA", "XIII Región Metropolitana de Santiago"),
                            (
                                "OHIGGINS",
                                "VI Región del Libertador General Bernardo O´Higgins",
                            ),
                            ("MAULE", "VII Región del Maule"),
                            ("NUBLE", "XVI Región de Ñuble"),
                            ("BIOBIO", "VIII Región del Biobío"),
                            ("ARAUCANIA", "IX Región de La Araucanía"),
                            ("LOS_RIOS", "XIV Región de Los Ríos"),
                            ("LOS_LAGOS", "X Región de Los Lagos"),
                            ("AYSEN", "XI Región de Aysén"),
                            (
                                "MAGALLANES",
                                "XII Región de Magallanes y la Antártica Chilena",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("contacto", models.CharField(max_length=50)),
                (
                    "terminos_de_pago",
                    models.TextField(help_text="Seleccione el tipo de pago"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=16, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("precio_costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField()),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InvoPro.departamento",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InvoPro.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_lote", models.CharField(max_length=16, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_vencimiento", models.DateField()),
                ("fecha_fabricacion", models.DateField()),
                ("cantidad_productos", models.CharField(max_length=10)),
                ("cantidad_disponible", models.CharField(max_length=10)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="InvoPro.producto",
                    ),
                ),
            ],
        ),
    ]
