# Generated by Django 5.0.7 on 2024-11-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InvoPro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_costo",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
