# Generated by Django 5.0.7 on 2024-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InvoPro", "0003_alter_producto_precio_costo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_costo",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.IntegerField(),
        ),
    ]
