# Generated by Django 5.0.7 on 2024-11-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InvoPro", "0004_alter_producto_precio_costo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lote",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_costo",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.CharField(max_length=10),
        ),
    ]
