# Generated by Django 5.0.7 on 2024-11-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InvoPro", "0005_alter_lote_descripcion_alter_producto_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="InvoPro.departamento",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="InvoPro.proveedor",
            ),
        ),
    ]
