# Generated by Django 5.0.7 on 2024-11-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InvoPro", "0006_alter_producto_departamento_alter_producto_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="InvoPro.departamento"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="InvoPro.proveedor"
            ),
        ),
    ]
